### ISSUE TITLE
e para quem não sabe?

### ISSUE THREAD

**Issue by raphamorim** [andrewsmedina/go-para-quem-sabe-go#1]

**Comment by andrewsmedina** [comment]
esse projeto é o material do workshop que acontecerá na Gophercon Brasil 2017: https://2017.gopherconbr.org/

pode ser que depois desse workshop feito eu possa dedicar tempo para fazer um material de Go para quem não sabe Go

**Comment by raphamorim** [comment]
Ah que massa,
estou começando na área de TI agora, se puder quero acompanhar sim!

Obrigado @andrewsmedina <3
